### ISSUE TITLE
Spongeforge 1.8.9 - 1762 + Kreezcrafts 1.8.9 Skycraft 1.80

### ISSUE THREAD

**Issue by celinor1982** [celinor1982/Minecraft#1]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreXU2 (extrautils2-1.8.9-alpha-0.0.2.jar)
  TrashSlot (trashslot-1.8.9-2.0.11.jar)
  FldLoadingPlugin (fastleafdecay-1.8-1.6.jar)
  EnderCorePlugin (ender-core-1.8.9-0.3.0.14-beta.jar)
  thaumicinfusion (thaumic-infusion-1.8.9-4.88.jar)
  BookshelfLoadingPlugin (bookshelf-1.8.9-1.1.2.207.jar)
  NowWithRendering (hopperducts-mc1.8.8-1.4.6.jar)
  SpongeCoremod (spongeforge-1.8.9-1890-4.2.0-BETA-1762.jar)
  LoadingPlugin (randomthings-mc1.8.9-3.6.6.jar)
  ThaumcraftLoader (thaumcraft-1.8.9-5.2.4.jar)
  MalisisCorePlugin (malisis-core-1.8.9-2.1.6.jar)
  MalisisSwitchesPlugin (malisisswitches-1.8.9-1.0.1.jar)
  ShadowMCCore (shadowmc-1.8.9-3.0.0-snapshot.jar)
  TransformerLoader (open-computers-1.8.9-1.6.0.8-rc.1.jar)
  NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
  TweaksLoadingPlugin (cctweaks-1.8.9-1.0.1.jar)
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 10/11/16 10:10 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderException: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) An exception was caught and reported. Message: org.spongepowered.mod.SpongeMod cannot be cast to org.spongepowered.api.plugin.PluginContainer
  at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)

2) No implementation for org.spongepowered.api.plugin.PluginContainer annotated with @com.google.inject.name.Named(value=sponge) was bound.
  at org.spongepowered.mod.guice.SpongeGuiceModule.configure(SpongeGuiceModule.java:68)

2 errors
    at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:344)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:488)
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:320)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:112)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441)
    at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) An exception was caught and reported. Message: org.spongepowered.mod.SpongeMod cannot be cast to org.spongepowered.api.plugin.PluginContainer
  at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)

2) No implementation for org.spongepowered.api.plugin.PluginContainer annotated with @com.google.inject.name.Named(value=sponge) was bound.
  at org.spongepowered.mod.guice.SpongeGuiceModule.configure(SpongeGuiceModule.java:68)

2 errors
    at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:466)
    at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
    at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
    at com.google.inject.Guice.createInjector(Guice.java:96)
    at com.google.inject.Guice.createInjector(Guice.java:73)
    at com.google.inject.Guice.createInjector(Guice.java:62)
    at org.spongepowered.mod.SpongeMod.<init>(SpongeMod.java:124)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at java.lang.Class.newInstance(Class.java:442)
    at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:339)
    ... 6 more
Caused by: java.lang.ClassCastException: org.spongepowered.mod.SpongeMod cannot be cast to org.spongepowered.api.plugin.PluginContainer
    at org.spongepowered.mod.guice.SpongeGuiceModule.configure(SpongeGuiceModule.java:68)
    at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
    at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
    at com.google.inject.spi.Elements.getElements(Elements.java:110)
    at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
    at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
    ... 16 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Linux (amd64) version 2.6.32-042stab116.2
    Java Version: 1.8.0_102, Oracle Corporation
    Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 917054216 bytes (874 MB) / 1060372480 bytes (1011 MB) up to 6429081600 bytes (6131 MB)
    JVM Flags: 9 total; -XX:-UseGCOverheadLimit -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -Xmx6G -Xms1G -Xss1M -XX:MaxPermSize=256M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.19 Powered by Forge 11.15.1.1890 4 mods loaded, 0 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
        mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
        FML{8.0.99.99} [Forge Mod Loader](skycraft_189.jar) 
        Forge{11.15.1.1890} [Minecraft Forge](skycraft_189.jar) 
        OpenComputers|Core{1.6.0.8-rc.1} [OpenComputers (Core)](minecraft.jar) 
    Loaded coremods (and transformers): 
CoreXU2 (extrautils2-1.8.9-alpha-0.0.2.jar)
  com.rwtema.extrautils2.asm.ClassTransformerHandler
TrashSlot (trashslot-1.8.9-2.0.11.jar)
  net.blay09.mods.trashslot.coremod.MinecraftClassTransformer
FldLoadingPlugin (fastleafdecay-1.8-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
EnderCorePlugin (ender-core-1.8.9-0.3.0.14-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
thaumicinfusion (thaumic-infusion-1.8.9-4.88.jar)
  drunkmafia.thaumicinfusion.common.asm.BlockTransformer
  drunkmafia.thaumicinfusion.common.asm.WorldTransformer
BookshelfLoadingPlugin (bookshelf-1.8.9-1.1.2.207.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
NowWithRendering (hopperducts-mc1.8.8-1.4.6.jar)
  net.fybertech.nwr.NowWithRendering
SpongeCoremod (spongeforge-1.8.9-1890-4.2.0-BETA-1762.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
LoadingPlugin (randomthings-mc1.8.9-3.6.6.jar)
  lumien.randomthings.asm.ClassTransformer
ThaumcraftLoader (thaumcraft-1.8.9-5.2.4.jar)

MalisisCorePlugin (malisis-core-1.8.9-2.1.6.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
MalisisSwitchesPlugin (malisisswitches-1.8.9-1.0.1.jar)
  net.malisis.switches.asm.MalisisSwitchesTransformer
ShadowMCCore (shadowmc-1.8.9-3.0.0-snapshot.jar)
  net.shadowfacts.shadowmc.core.ShadowMCTransformer
TransformerLoader (open-computers-1.8.9-1.6.0.8-rc.1.jar)
  li.cil.oc.common.asm.ClassTransformer
NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
  net.fybertech.nwr.NowWithRendering
TweaksLoadingPlugin (cctweaks-1.8.9-1.0.1.jar)
  org.squiddev.cctweaks.core.asm.ASMTransformer
    Profiler Position: N/A (disabled)
    Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
    Type: Dedicated Server (map_server.txt)

**Comment by celinor1982** [comment]
Automated Redstone 3.1.4 - Circuits 3.0.1 causes SpongeForge to crash the server and not load.

**Comment by celinor1982** [comment]
**Ender-Core-1.8.9-0.3.0.14-beta:**

[12:10:15] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.mixin.MixinEnvironment$EnvironmentStateTweaker
[12:10:17] [main/INFO] [EnderCore]: Transforming Class [net.minecraft.item.ItemStack], Method [func_77953_t]
[12:10:17] [main/INFO] [EnderCore]: Transforming net.minecraft.item.ItemStack Finished.
[12:10:17] [main/INFO] [mixin]: A re-entrant transformer '$wrapper.com.enderio.core.common.transform.EnderCoreTransformer' was detected and will no longer process meta class data
[12:10:22] [main/INFO] [mixin]: Instancing error handler class org.spongepowered.mod.mixin.handler.MixinErrorHandler
[12:10:22] [main/INFO] [Sponge]: /****************************************************************************************************************************************************************************************_/
[12:10:22] [main/INFO] [Sponge]: /_                                                                                                                                                                                       _/
[12:10:22] [main/INFO] [Sponge]: /_ Oh dear. Something went wrong and the server had to shut down!                                                                                                                        _/
[12:10:22] [main/INFO] [Sponge]: /_                                                                                                                                                                                       _/
[12:10:22] [main/INFO] [Sponge]: /_---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------_/
[12:10:22] [main/INFO] [Sponge]: /_                                                                                                                                                                                       _/
[12:10:22] [main/INFO] [Sponge]: /_ A critical error was encountered while blending Sponge with Forge!                                                                                                                    _/
[12:10:22] [main/INFO] [Sponge]: /_                                                                                                                                                                                       _/
[12:10:22] [main/INFO] [Sponge]: /_   Possible causes are:                                                                                                                                                                _/
[12:10:22] [main/INFO] [Sponge]: /_                                                                                                                                                                                       _/
[12:10:22] [main/INFO] [Sponge]: /_    \* An incompatible Forge "core mod" is present. Try removing other mods to                                                                                                          _/
[12:10:22] [main/INFO] [Sponge]: /_      see if the problem goes away.                                                                                                                                                    _/
[12:10:22] [main/INFO] [Sponge]: /_                                                                                                                                                                                       _/
[12:10:22] [main/INFO] [Sponge]: /_    \* You are using the wrong version of Minecraft Forge. You must use the                                                                                                             _/
[12:10:22] [main/INFO] [Sponge]: /_      correct version of Forge when running Sponge, this version is for                                                                                                                _/
[12:10:22] [main/INFO] [Sponge]: /_      11.15.1.1890-1.8.9 (you are running 11.15.1.1890)                                                                                                                                _/
[12:10:22] [main/INFO] [Sponge]: /_                                                                                                                                                                                       _/
[12:10:22] [main/INFO] [Sponge]: /_    \* An error exists in Sponge itself. Ensure you are running the latest version                                                                                                      _/
[12:10:22] [main/INFO] [Sponge]: /_      of Sponge.                                                                                                                                                                       _/
[12:10:22] [main/INFO] [Sponge]: /_                                                                                                                                                                                       _/
[12:10:22] [main/INFO] [Sponge]: /_    \* Gremlins are invading your computer. Did you feed a Mogwai after midnight?                                                                                                       _/
[12:10:22] [main/INFO] [Sponge]: /_                                                                                                                                                                                       _/
[12:10:22] [main/INFO] [Sponge]: /_---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------_/
[12:10:22] [main/INFO] [Sponge]: /_                                                                                                                                                                                       _/
[12:10:22] [main/INFO] [Sponge]: /_ Technical details:                                                                                                                                                                    _/
[12:10:22] [main/INFO] [Sponge]: /_                                                                                                                                                                                       _/
[12:10:22] [main/INFO] [Sponge]: /_      Failed on class : N/A                                                                                                                                                            _/
[12:10:22] [main/INFO] [Sponge]: /_         During phase : DEFAULT                                                                                                                                                        _/
[12:10:22] [main/INFO] [Sponge]: /_                Mixin : event.state.MixinEventInit                                                                                                                                     _/
[12:10:22] [main/INFO] [Sponge]: /_               Config : mixins.forge.core.json                                                                                                                                         _/
[12:10:22] [main/INFO] [Sponge]: /_           Error Type : org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException                                                                           _/
[12:10:22] [main/INFO] [Sponge]: /_            Caused by : Unknown                                                                                                                                                        _/
[12:10:22] [main/INFO] [Sponge]: /_              Message : Critical problem: mixins.forge.core.json:event.state.MixinEventInit target net.minecraftforge.fml.common.event.FMLInitializationEvent was already transformed. _/
[12:10:22] [main/INFO] [Sponge]: /_                                                                                                                                                                                       */
[12:10:22] [main/INFO] [Sponge]: /*****************************************************************************************************************************************************************************************/
[12:10:22] [main/INFO] [FML]: Java has been asked to exit (code 1) by net.minecraftforge.fml.common.FMLCommonHandler.exitJava(FMLCommonHandler.java:648).
[12:10:22] [main/INFO] [FML]: This is an abortive exit and could cause world corruption or other things
[12:10:22] [main/INFO] [FML]: If this was an unexpected exit, use -Dfml.debugExit=true as a JVM argument to find out where it was called
[celinor1982@midgard skycraft_180]$

**Comment by celinor1982** [comment]
**extrautils2-1.8.0-alpha-0.0.2 alpha:**

[12:27:05] [main/INFO] [ExtraUtils2CoreMod]: XU Transformer: adm(net.minecraft.world.World) {com.rwtema.extrautils2.asm.LightingTransformer@4108fa66}
[12:27:05] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
[12:27:10] [main/INFO] [ShadowMC|Core]: Transforming net.minecraft.item.ItemTool
[12:27:10] [main/INFO] [ShadowMC|Core]: Finish transforming net.minecraft.item.ItemTool
[12:27:14] [Server thread/INFO]: Starting minecraft server version 1.8.9
[12:27:14] [Server thread/INFO] [FML]: MinecraftForge v11.15.1.1890 Initialized
[12:27:14] [Server thread/INFO] [FML]: Replaced 229 ore recipies

> Oct 12, 2016 12:27:19 PM com.google.inject.internal.MessageProcessor visit
> INFO: An exception was caught and reported. Message: java.lang.ClassCastException: org.spongepowered.mod.SpongeMod cannot be cast to org.spongepowered.api.plugin.PluginContainer
> java.lang.ClassCastException: org.spongepowered.mod.SpongeMod cannot be cast to org.spongepowered.api.plugin.PluginContainer
>     at org.spongepowered.mod.guice.SpongeGuiceModule.configure(SpongeGuiceModule.java:68)
>     at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
>     at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
>     at com.google.inject.spi.Elements.getElements(Elements.java:110)
>     at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
>     at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
>     at com.google.inject.Guice.createInjector(Guice.java:96)
>     at com.google.inject.Guice.createInjector(Guice.java:73)
>     at com.google.inject.Guice.createInjector(Guice.java:62)
>     at org.spongepowered.mod.SpongeMod.<init>(SpongeMod.java:124)
>     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
>     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
>     at java.lang.Class.newInstance(Class.java:442)
>     at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:339)
>     at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:488)
>     at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
>     at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:320)
>     at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:112)
>     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441)
>     at java.lang.Thread.run(Thread.java:745)

[12:27:20] [Server thread/ERROR] [FML]: A problem occured instantiating the injected mod container org.spongepowered.mod.SpongeMod
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) An exception was caught and reported. Message: org.spongepowered.mod.SpongeMod cannot be cast to org.spongepowered.api.plugin.PluginContainer
  at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)

2) No implementation for org.spongepowered.api.plugin.PluginContainer annotated with @com.google.inject.name.Named(value=sponge) was bound.
  at org.spongepowered.mod.guice.SpongeGuiceModule.configure(SpongeGuiceModule.java:68)

2 errors
    at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:466) ~[Errors.class:1.8.9-1890-4.2.0-BETA-1762]
    at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155) ~[InternalInjectorCreator.class:1.8.9-1890-4.2.0-BETA-1762]
    at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107) ~[InternalInjectorCreator.class:1.8.9-1890-4.2.0-BETA-1762]
    at com.google.inject.Guice.createInjector(Guice.java:96) ~[Guice.class:1.8.9-1890-4.2.0-BETA-1762]
    at com.google.inject.Guice.createInjector(Guice.java:73) ~[Guice.class:1.8.9-1890-4.2.0-BETA-1762]
    at com.google.inject.Guice.createInjector(Guice.java:62) ~[Guice.class:1.8.9-1890-4.2.0-BETA-1762]
    at org.spongepowered.mod.SpongeMod.<init>(SpongeMod.java:124) ~[SpongeMod.class:1.8.9-1890-4.2.0-BETA-1762]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_102]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_102]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_102]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_102]
    at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_102]
    at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:339) [Loader.class:?]
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:488) [Loader.class:?]
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87) [FMLServerHandler.class:?]
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:320) [FMLCommonHandler.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:112) [ko.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
Caused by: java.lang.ClassCastException: org.spongepowered.mod.SpongeMod cannot be cast to org.spongepowered.api.plugin.PluginContainer
    at org.spongepowered.mod.guice.SpongeGuiceModule.configure(SpongeGuiceModule.java:68) ~[SpongeGuiceModule.class:1.8.9-1890-4.2.0-BETA-1762]
    at com.google.inject.AbstractModule.configure(AbstractModule.java:62) ~[AbstractModule.class:1.8.9-1890-4.2.0-BETA-1762]
    at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340) ~[Elements$RecordingBinder.class:1.8.9-1890-4.2.0-BETA-1762]
    at com.google.inject.spi.Elements.getElements(Elements.java:110) ~[Elements.class:1.8.9-1890-4.2.0-BETA-1762]
    at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138) ~[InjectorShell$Builder.class:1.8.9-1890-4.2.0-BETA-1762]
    at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104) ~[InternalInjectorCreator.class:1.8.9-1890-4.2.0-BETA-1762]
    ... 16 more
[12:27:20] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraftforge.fml.common.LoaderException: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) An exception was caught and reported. Message: org.spongepowered.mod.SpongeMod cannot be cast to org.spongepowered.api.plugin.PluginContainer
  at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)

2) No implementation for org.spongepowered.api.plugin.PluginContainer annotated with @com.google.inject.name.Named(value=sponge) was bound.
  at org.spongepowered.mod.guice.SpongeGuiceModule.configure(SpongeGuiceModule.java:68)

2 errors

```
at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:344) ~[Loader.class:?]
at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:488) ~[Loader.class:?]
at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87) ~[FMLServerHandler.class:?]
at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:320) ~[FMLCommonHandler.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:112) ~[ko.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
```

Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) An exception was caught and reported. Message: org.spongepowered.mod.SpongeMod cannot be cast to org.spongepowered.api.plugin.PluginContainer
  at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)

2) No implementation for org.spongepowered.api.plugin.PluginContainer annotated with @com.google.inject.name.Named(value=sponge) was bound.
  at org.spongepowered.mod.guice.SpongeGuiceModule.configure(SpongeGuiceModule.java:68)

2 errors
    at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:466) ~[Errors.class:1.8.9-1890-4.2.0-BETA-1762]
    at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155) ~[InternalInjectorCreator.class:1.8.9-1890-4.2.0-BETA-1762]
    at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107) ~[InternalInjectorCreator.class:1.8.9-1890-4.2.0-BETA-1762]
    at com.google.inject.Guice.createInjector(Guice.java:96) ~[Guice.class:1.8.9-1890-4.2.0-BETA-1762]
    at com.google.inject.Guice.createInjector(Guice.java:73) ~[Guice.class:1.8.9-1890-4.2.0-BETA-1762]
    at com.google.inject.Guice.createInjector(Guice.java:62) ~[Guice.class:1.8.9-1890-4.2.0-BETA-1762]
    at org.spongepowered.mod.SpongeMod.<init>(SpongeMod.java:124) ~[SpongeMod.class:1.8.9-1890-4.2.0-BETA-1762]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_102]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_102]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_102]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_102]
    at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_102]
    at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:339) ~[Loader.class:?]
    ... 6 more
Caused by: java.lang.ClassCastException: org.spongepowered.mod.SpongeMod cannot be cast to org.spongepowered.api.plugin.PluginContainer
    at org.spongepowered.mod.guice.SpongeGuiceModule.configure(SpongeGuiceModule.java:68) ~[SpongeGuiceModule.class:1.8.9-1890-4.2.0-BETA-1762]
    at com.google.inject.AbstractModule.configure(AbstractModule.java:62) ~[AbstractModule.class:1.8.9-1890-4.2.0-BETA-1762]
    at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340) ~[Elements$RecordingBinder.class:1.8.9-1890-4.2.0-BETA-1762]
    at com.google.inject.spi.Elements.getElements(Elements.java:110) ~[Elements.class:1.8.9-1890-4.2.0-BETA-1762]
    at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138) ~[InjectorShell$Builder.class:1.8.9-1890-4.2.0-BETA-1762]
    at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104) ~[InternalInjectorCreator.class:1.8.9-1890-4.2.0-BETA-1762]
    at com.google.inject.Guice.createInjector(Guice.java:96) ~[Guice.class:1.8.9-1890-4.2.0-BETA-1762]
    at com.google.inject.Guice.createInjector(Guice.java:73) ~[Guice.class:1.8.9-1890-4.2.0-BETA-1762]
    at com.google.inject.Guice.createInjector(Guice.java:62) ~[Guice.class:1.8.9-1890-4.2.0-BETA-1762]
    at org.spongepowered.mod.SpongeMod.<init>(SpongeMod.java:124) ~[SpongeMod.class:1.8.9-1890-4.2.0-BETA-1762]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_102]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_102]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_102]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_102]
    at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_102]
    at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:339) ~[Loader.class:?]
    ... 6 more
[12:27:20] [Server thread/ERROR]: This crash report has been saved to: /home/celinor1982/Desktop/skycraft_180/./crash-reports/crash-2016-10-12_12.27.20-server.txt
[12:27:20] [Server thread/WARN] [FML]: Can't revert to frozen GameData state without freezing first.
[12:27:20] [Server thread/INFO] [FML]: The state engine was in incorrect state CONSTRUCTING and forced into state SERVER_STOPPED. Errors may have been discarded.
